### ISSUE TITLE
slugify_unicode in NVD3Chart.py

### ISSUE THREAD

**Issue by alpha-beta-soup** [areski/python-nvd3#76]
I'm getting an error as follows when I try to use NVD3Chart.py:

```bash
from .NVD3Chart import NVD3Chart
  File "/usr/local/lib/python2.7/dist-packages/nvd3/NVD3Chart.py", line 15, in <module>
    from slugify import slugify_unicode
ImportError: cannot import name slugify_unicode
```

Indeed:
```python
>>> from slugify import slugify_unicode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name slugify_unicode
```

slugify.slugify_unicode is being used once as follows: 
```python
from slugify import slugify_unicode
def slugify_name(self, name):
        """Slufigy name with underscore"""
        self.name = slugify_unicode(name, separator='_')
```

So this is a simple fix:
```python
import slugify
def slugify_name(self, name):
        """Slufigy name with underscore"""
        self.name = slugify.slugify(name, separator='_')
```

The fix works for me without any new issues.

**Comment by oz123** [comment]
this fix is already applied in `master`
